# Generated by Django 2.1.4 on 2019-01-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_landsatsetting_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landsatsetting',
            old_name='name',
            new_name='config_name',
        ),
        migrations.AddField(
            model_name='sentinelsetting',
            name='config_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
