# Generated by Django 2.1.4 on 2019-01-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190103_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='landsatsetting',
            name='default_config',
            field=models.BooleanField(default=False),
        ),
    ]
