# Generated by Django 2.1.4 on 2019-01-03 08:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0004_landsatsetting_default_config'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandsatSetting',
            new_name='Landsat2',
        ),
        migrations.RenameModel(
            old_name='SentinelSetting',
            new_name='Sentinel2',
        ),
    ]
