# Generated by Django 2.1.4 on 2019-01-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20190103_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landsat2',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='sentinel2',
            name='sensor',
        ),
        migrations.AddField(
            model_name='sentinel2',
            name='default_config',
            field=models.BooleanField(default=False),
        ),
    ]
