# Generated by Django 2.1.4 on 2019-01-03 09:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0006_auto_20190103_1005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Landsat2',
            new_name='Landsat8',
        ),
    ]
