# Generated by Django 2.1.4 on 2019-01-25 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor_configs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersensor',
            name='sensors',
            field=models.ManyToManyField(to='sensor_configs.Sensor'),
        ),
        migrations.AddField(
            model_name='usersensor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproject',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_configs.Sensor'),
        ),
        migrations.AddField(
            model_name='userproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproject',
            name='watertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_configs.Watertype'),
        ),
        migrations.AlterUniqueTogether(
            name='userproject',
            unique_together={('user', 'user_project_name')},
        ),
    ]
