# Generated by Django 2.1.4 on 2019-01-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_configs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configlandsat8',
            name='main_watertype',
            field=models.IntegerField(choices=[(4, 'Global Type'), (42, 'Mixed Type'), (82, 'River Type')], default=4, help_text='Original water type to be used for retrieval of water constituents'),
        ),
        migrations.AlterField(
            model_name='configsentinel2',
            name='config_name',
            field=models.CharField(default='Default', max_length=200),
        ),
        migrations.AlterField(
            model_name='configsentinel2',
            name='main_watertype',
            field=models.IntegerField(choices=[(4, 'Global Type'), (42, 'Mixed Type'), (82, 'River Type')], default=4, help_text='Original water type to be used for retrieval of water constituents'),
        ),
        migrations.AlterField(
            model_name='configsentinel2',
            name='project_name',
            field=models.CharField(blank=True, help_text='Detailed description', max_length=200, null=True),
        ),
    ]
