# Generated by Django 2.1.4 on 2019-01-26 15:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190125_1555'),
        ('sensor_configs', '0002_auto_20190125_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ews_ident', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('json_configs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.UserProject')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='configlandsat8',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='configlandsat8',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='configsentinel2',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='configsentinel2',
            name='project',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='config_model',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='geodata_model',
        ),
        migrations.AddField(
            model_name='sensor',
            name='config_name',
            field=models.CharField(choices=[('landsat8.json', 'landsat8'), ('sentinel2.json', 'sentinel2')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConfigLandsat8',
        ),
        migrations.DeleteModel(
            name='ConfigSentinel2',
        ),
    ]
