# Generated by Django 2.1.4 on 2019-01-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190125_1555'),
        ('sensor_configs', '0003_auto_20190126_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='config',
            unique_together={('user_project', 'name')},
        ),
    ]
