# Generated by Django 2.1.4 on 2019-01-29 17:17

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_configs', '0005_auto_20190128_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
