# Generated by Django 2.1.4 on 2019-02-03 17:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190125_1555'),
        ('sensor_configs', '0006_sensor_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ews_ident', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('default', models.BooleanField(default=False)),
                ('json_configs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.UserProject')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='masking',
            unique_together={('user_project', 'name')},
        ),
    ]
