# Generated by Django 2.1.4 on 2019-02-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_configs', '0007_auto_20190203_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='config_name',
            field=models.CharField(choices=[('landsat8.json', 'landsat8'), ('sentinel2.json', 'sentinel2'), ('sentinel3.json', 'sentinel3')], max_length=255),
        ),
    ]
