# Generated by Django 2.1.4 on 2019-02-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_configs', '0009_auto_20190205_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='imgpart',
            field=models.ForeignKey(blank=True, help_text='Process only a pre-defined area of interest (AOI), provided as a ESRI Shapefile.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imgpart', to='geodata.UserProjectShape'),
        ),
        migrations.AlterField(
            model_name='config',
            name='mask_image',
            field=models.ForeignKey(blank=True, help_text='Mask out regions that shall not be processed by defining a precise area of interest, e.g. the exact water body you are interested in.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mask_image', to='geodata.UserProjectShape'),
        ),
        migrations.AlterField(
            model_name='config',
            name='polygonstatistics',
            field=models.ForeignKey(blank=True, help_text='Calculate statistics within specific regions, defined as single features within an ESRI Shapefile.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polygonstatistics', to='geodata.UserProjectShape'),
        ),
    ]
