# Generated by Django 2.1.4 on 2019-02-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0009_auto_20190205_1307'),
        ('sensor_configs', '0010_auto_20190206_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='static_mask',
            field=models.ForeignKey(blank=True, help_text='Use static shapes for product masking, e.g. shallow water areas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_mask', to='geodata.UserProjectShape'),
        ),
    ]
