# Generated by Django 2.1.4 on 2019-02-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_configs', '0011_config_static_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watertype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
