# Generated by Django 2.1.4 on 2019-10-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0009_auto_20190205_1307'),
        ('sensor_configs', '0013_auto_20190731_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='imgpart',
        ),
        migrations.RemoveField(
            model_name='config',
            name='mask_image',
        ),
        migrations.RemoveField(
            model_name='config',
            name='polygonstatistics',
        ),
        migrations.RemoveField(
            model_name='config',
            name='static_mask',
        ),
        migrations.AddField(
            model_name='config',
            name='aoi',
            field=models.ForeignKey(blank=True, help_text='Define area of Interest.', null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.UserProjectShape'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='config_name',
            field=models.CharField(choices=[('sentinel2.json', 'sentinel2')], max_length=255),
        ),
    ]
