# Generated by Django 2.1.4 on 2019-01-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EwsProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=40)),
                ('pc_hostname', models.CharField(max_length=30)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('ews_name', models.CharField(max_length=8, unique=True)),
                ('user_project_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ews_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ignore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ignore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagepart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ul_lon', models.FloatField()),
                ('ul_lat', models.FloatField()),
                ('lr_lon', models.FloatField()),
                ('lr_lat', models.FloatField()),
            ],
            options={
                'db_table': 'imagepart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.IntegerField(blank=True, null=True)),
                ('jobfile', models.IntegerField(blank=True, null=True)),
                ('qflag_cfg', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('stop_action', models.CharField(blank=True, max_length=500, null=True)),
                ('start_action', models.CharField(blank=True, max_length=500, null=True)),
                ('waterglob_cfg', models.IntegerField(blank=True, null=True)),
                ('waterdetect_cfg', models.IntegerField(blank=True, null=True)),
                ('wstaubig_cfg', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogAdm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('ews_project', models.IntegerField(blank=True, null=True)),
                ('modul', models.CharField(blank=True, max_length=50, null=True)),
                ('function', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'log_adm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogMissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('mission', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('modul', models.CharField(blank=True, max_length=50, null=True)),
                ('function', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'log_missions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('ews_project', models.IntegerField(blank=True, null=True)),
                ('modul', models.CharField(blank=True, max_length=50, null=True)),
                ('function', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'log_server',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectxml', models.CharField(max_length=255)),
                ('ident', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('jd', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('actiondatetime', models.DateTimeField(blank=True, null=True)),
                ('actiondescription', models.CharField(blank=True, max_length=255, null=True)),
                ('actionname', models.CharField(blank=True, max_length=255, null=True)),
                ('activeaction', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=3, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'project_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectXml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcedir', models.CharField(max_length=200)),
                ('importdir', models.CharField(max_length=200)),
                ('exportdir', models.CharField(max_length=200)),
                ('bindir', models.CharField(max_length=200)),
                ('dimapdir', models.CharField(max_length=200)),
                ('missionrootdir', models.CharField(max_length=200)),
                ('rootdir', models.CharField(max_length=200)),
                ('defaultmissiondir', models.CharField(max_length=200)),
                ('serverport', models.IntegerField()),
                ('servermode_auto', models.CharField(blank=True, max_length=10, null=True)),
                ('jobmode_foreground', models.CharField(blank=True, max_length=10, null=True)),
                ('jobmode_autoexit', models.CharField(blank=True, max_length=10, null=True)),
                ('cpus', models.IntegerField(blank=True, null=True)),
                ('sourcecheckintervall', models.IntegerField()),
                ('orderdelay', models.IntegerField()),
                ('queuedir', models.CharField(max_length=200)),
                ('ignoreorderdir', models.CharField(max_length=200)),
                ('colorpalettegray', models.CharField(max_length=200)),
                ('colorpalettecolor', models.CharField(max_length=200)),
                ('colorpaletteflag', models.CharField(blank=True, max_length=200, null=True)),
                ('colorpalettediff', models.CharField(blank=True, max_length=200, null=True)),
                ('gain', models.IntegerField(blank=True, null=True)),
                ('colorpalettetsm', models.CharField(blank=True, max_length=200, null=True)),
                ('colorpalettephy', models.CharField(blank=True, max_length=200, null=True)),
                ('colorpalettecdm', models.CharField(blank=True, max_length=200, null=True)),
                ('colorpalettequc', models.CharField(blank=True, max_length=200, null=True)),
                ('colorpalettequt', models.CharField(blank=True, max_length=200, null=True)),
                ('colorpalettez90', models.CharField(blank=True, max_length=200, null=True)),
                ('jobmode_cleanup', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'project_xml',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=40)),
                ('resolution', models.IntegerField()),
            ],
            options={
                'db_table': 'sensor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'water_type',
                'managed': False,
            },
        ),
    ]
