# Generated by Django 2.1.4 on 2019-01-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ews_db_connector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulx', models.FloatField(blank=True, null=True)),
                ('uly', models.FloatField(blank=True, null=True)),
                ('lrx', models.FloatField(blank=True, null=True)),
                ('lry', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cloud_cover', models.FloatField(blank=True, null=True)),
                ('query_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'download_query',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=1000, null=True)),
                ('download_state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'file_download',
                'managed': False,
            },
        ),
    ]
