# Generated by Django 2.1.4 on 2019-02-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_download_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cpu_cores',
            field=models.IntegerField(default=6),
        ),
    ]
