# Generated by Django 2.1.4 on 2019-02-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_cpu_cores'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ews_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
