# Generated by Django 2.1.4 on 2019-07-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_ews_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_continous_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='min_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='download_region',
            field=models.ManyToManyField(blank=True, null=True, to='geodata.Country'),
        ),
    ]
