# Generated by Django 2.1.4 on 2019-08-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190731_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temporal_licence',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
