# Generated by Django 2.1.4 on 2019-08-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_temporal_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='temporal_licence',
            field=models.DateField(blank=True, null=True),
        ),
    ]
