# Generated by Django 2.1.4 on 2019-01-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_auto_20190130_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
