# Generated by Django 2.1.4 on 2019-01-31 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0005_auto_20190130_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country_code']},
        ),
    ]
