# Generated by Django 2.1.4 on 2019-02-05 11:44

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190125_1555'),
        ('geodata', '0006_auto_20190131_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('user_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.UserProject')),
            ],
        ),
        migrations.CreateModel(
            name='UserProjectShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('geometry', models.ManyToManyField(to='geodata.UserData')),
                ('user_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.UserProject')),
            ],
        ),
    ]
