# Generated by Django 2.1.4 on 2019-02-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0007_userdata_userprojectshape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user_project',
        ),
        migrations.RemoveField(
            model_name='userprojectshape',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='userprojectshape',
            name='user_project',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.DeleteModel(
            name='UserProjectShape',
        ),
    ]
