# Generated by Django 2.1.4 on 2019-02-05 12:07

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190125_1555'),
        ('geodata', '0008_auto_20190205_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='UserProjectShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('json_geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.UserProject')),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.UserProjectShape'),
        ),
    ]
