# Generated by Django 2.1.4 on 2019-02-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissionActionBlock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_after_block', models.BooleanField(default=False)),
                ('block_name', models.IntegerField(blank=True, choices=[(1, 'Scene clipping and masking'), (2, 'Regfil'), (3, 'Land-Water-Mask'), (4, 'Adjacency correction'), (5, 'Glint Correction'), (6, 'Water Species Retrieval')], default=None, null=True)),
            ],
        ),
    ]
