# Generated by Django 2.1.4 on 2019-02-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_configs', '0010_auto_20190206_1806'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionactionblock',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor_configs.Config'),
        ),
        migrations.AddField(
            model_name='missionactionblock',
            name='masking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor_configs.Masking'),
        ),
    ]
