# Generated by Django 2.1.4 on 2019-02-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_auto_20190206_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionactionblock',
            name='block_name',
            field=models.IntegerField(blank=True, choices=[(1, 'RGB Creation'), (2, 'Land-Water-Mask'), (3, 'Glint Correction'), (4, 'Product Generation')], default=None, null=True),
        ),
    ]
